"""
Django settings for tonino project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wv*lgzd8g8qmg3uvpx8a2z2o6ie$xln!4q1pr0ve2x0rbmdfmy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'suit',
    #'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django.contrib.humanize',
    'django.contrib.admindocs',

    'ajax_select',
    'smart_selects',
    'widget_tweaks',
    'nucleo',
    'gestion',
    'control',
    'permisos',
    'rubro',
    'proovedores',
    'contabilidad',
    'recepcion',
    'clientes',
    'despacho',
    'administracion',
    'plantas',


)    

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'tonino.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.normpath(os.path.join(os.path.dirname(__file__),'../template'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'django.template.context_processors.request'
                'django.core.context_processors.request',
                'nucleo.context_datos_principales.my_processor',
              ],
        },
    },
]



 # Django Suit configuration example
SUIT_CONFIG = {
      # header
      'ADMIN_NAME': 'Django Suit',
      'HEADER_DATE_FORMAT': 'l, j. F Y',
      'HEADER_TIME_FORMAT': 'H:i',

      # forms
      'SHOW_REQUIRED_ASTERISK': True,  # Default True
       'CONFIRM_UNSAVED_CHANGES': True, # Default True

      # menu
     'SEARCH_URL': '/admin/auth/user/',
     'MENU_ICONS': {
         'sites': 'icon-leaf',
          'auth': 'icon-lock',
      },
      'MENU_OPEN_FIRST_CHILD': True, # Default True
      'MENU_EXCLUDE': ('auth.group',),
      'MENU': (
           'sites',
           {'app': 'auth', 'icon':'icon-lock', 'models': ('user', 'group')},
           {'label': 'Settings', 'icon':'icon-cog', 'models': ('auth.user', 'auth.group')},
           {'label': 'Support', 'icon':'icon-question-sign', 'url': '/support/'},
       ),

       #misc
       'LIST_PER_PAGE': 15
  }

WSGI_APPLICATION = 'tonino.wsgi.application'

USE_DJANGO_JQUERY=True
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        
    }
}
'''
DATABASES = { 
    'default': { 
       'ENGINE': 'django.db.backends.postgresql_psycopg2',#django.db.backends.mysql',# 
       'NAME': 'MOLIVEN', 
       'USER': 'moliven', 
      'PASSWORD': '1573837', 
      'HOST': 'localhost', 
      'PORT': '5432', 
    } 
}

AJAX_LOOKUP_CHANNELS = {
     'person' : ('example.lookups', 'PersonLookup'),
}
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT=os.path.normpath(os.path.join(os.path.dirname(__file__),'../nucleo/static/media/'))
MEDIA_URL = '/media/'
STATIC_ROOT = '/static/'